name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: go run cmd/main.go golang build --base-name cicd --os darwin --os linux --os windows --arch amd64 cmd/main.go

      - name: Test
        run: go run cmd/main.go golang run-tests
      
      - name: Show Coverage
        run: go tool cover -func=build/coverage/all.out

      - name: Calculate Next Version
        run: |
          go run cmd/main.go semantic-release version-file vinnieapps/cicd-toolbox
          cat .version

      - name: Change Log
        run: go run cmd/main.go semantic-release change-log vinnieapps/cicd-toolbox

      - name: Release
        if: github.ref == 'refs/heads/master'
        run: go run cmd/main.go semantic-release publish-release vinnieapps/cicd-toolbox --github-token ${{ secrets.GITHUB_TOKEN }} --upload build/binaries
