name: Pull Request Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Build
        run: go run cmd/main.go golang build --os darwin --os linux --os windows -a amd64 cmd/main.go

      - name: Test
        run: build/binaries/amd64_linux/main golang run-tests
      
      - name: Show Coverage
        run: go tool cover -func=build/coverage/all.out
